packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

catalog:
  "@tanstack/react-query": ^5.51.9
  "@trpc/client": ^11.0.0-rc.466
  "@trpc/react-query": ^11.0.0-rc.466
  "@trpc/server": ^11.0.0-rc.466
  superjson: ^2.2.1
  zod: ^3.23.8
  date-fns: ^3.6.0

  eslint: ^9.7.0
  prettier: ^3.3.3
  typescript: ^5.5.3
  rimraf: ^6.0.1
  tsup: ^8.1.0
  tailwindcss: ^3.4.4
  postcss: ^8.4.39
  autoprefixer: ^10.4.19

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
